export const NetworkConfig = {
    // BASE_URL: 'http://localhost:6021/api',
    // BASE_URL                : 'https://www.evento.sa/api',
    // MERCHANT_ID              : '3000000016',          // DEV
    // MERCHANT_JS             : "https://test-gateway.mastercard.com/checkout/version/51/checkout.js", // DEV
    BASE_URL                : '/api',
    LOGIN_URL               : '/auth',
    LOGOUT_URL              : '/auth/logout',
    FORGET_PASSWORD         : '/auth/forgot_password',
    REACTIVATE              : '/auth/reactivate',
    RESET_PASSWORD          : '/auth/reset_password/',
    ACTIVATE_ACCOUNT        : '/auth/activate_account/',
    EVENT                   : '/event',
    UPDATE_EVENT_INFO       : '/event/update_info/',
    UPDATE_EVENT_SETTING    : '/event/update_setting/',
    REQUEST                 : '/requests',
    CITY_LIST               : '/common/city',
    REGION_LIST             : '/common/regions',
    AUDIANCE_LIST           : '/common/audience',
    EVENT_TYPE              : '/common/event_types',
    QUESTIONS               : '/questions',
    EVENT_POLICIES          : '/event_policy/',
    CALENDAR                : '/calendar',
    PRE_ACCEPT_REQUESTS     : '/pre_accept/',
    REJECT_REQUEST          : '/reject/',
    FinalAccept             : '/final_accept/',
    RatingList              : '/rating_interview/',
    INTERVIEWS              : '/interviews/',
    RATING_QUESTION         : '/interviews/rating/',
    END_INTERVIEW           : '/interviews/end_interview/',
    PACKAGES                : '/packages/',
    GET_SELLER              : '/seller/getSeller/',
    CREATE_SELLER           : '/seller/createSeller/',
    UPDATE_SELLER           : '/seller/updateSeller/',
    CREATE_INVOICE          : '/seller/createInvoice/',
    LIST_INVOICE            : '/seller/invoices/',
    LAST_TICKET             : '/seller/tickets/',
    LIST_PACKAGES           : '/seller/listPackages/',
    CREATE_INVOICE_PAYMENT  : '/invoice/create',
    GET_MOBILE_INVOICE      : '/invoice/get_mobile_invoice',
    GET_INVOICE_DETAILS     : '/invoice/get_invoice',
    CHECK_INVOICE_STATUS    : '/invoice/check_invoice',
    UPDATE_INVOICE_MOYASAR  : '/invoice/update_invoice',
    SEARCH                  : '/home/search',
    VIEW_EVENT              : '/home/event/',
    SUBMIT_REQUEST          : '/home/submit_to_join/',
    CREATE_EVENT_INVOICE    : '/event/create_payment/',
    VALIDATE_EVENT_PAYMENT  : '/event/validate_payment/',
    CV                      : '/cv/',
    CREATE_CV               : '/cv/create_cv/',
    SKILLS                  : '/cv/skills',
    DELETE_SKILLS           : '/cv/delete_skills',
    EXPERIENCE              : '/cv/experience',
    DELETE_EXPERIENCE       : '/cv/delete_experience',
    QUALIFICATION           : '/cv/qualification',
    DELETE_QUALIFICATION    : '/cv/delete_qualification',
    USERS                   : '/users',
    NATIONALITIES           : '/common/nationality',
    EDUCATIONS              : '/common/educations',
    CONTACT_US              : '/contact/send',
    ADVERTIZED_EVENTS       : '/home/adds',
    LATEST_EVENTS           : '/home/latest',
    REPORTS_OVERVIEW        : '/report/overview/',
    REPORTS_DAILY           : '/report/groupByDate/',
    REPORTS_BY_PACKAGE      : '/report/groupByPackage/',
    REPORTS_SELLER          : '/report/seller/',
    LIST_SUPERVISORS        : '/supervisor/getSupervisors/',
    CREATE_SUPERVISOR       : '/supervisor/createSupervisors/',
    UPDATE_SUPERVISOR       : '/supervisor/updateSupervisors/',
    LIST_INVOCICE           : '/invoice/list',
    LIST_TICKETS_OF_INVOCE  : '/invoice/tickets',
    UPDATE_MOI_NUMBER       : '/event/update_moi/',
    TICKET_LIST             : '/event/event_tickets/',
    TICKET_DETAILS          : '/event/ticket/',
    UPDATE_EVENT_INVOICE    : '/event/update_invoice/',
    RATING_ORGANIZERS       : '/rating_organizers/',
    VALIDATE_PACKAGE        : '/home/validate-package/',
    SELLER_EVENT            : '/seller/sellerEvent/',
    SUPER_EVENT             : '/supervisor/superEvent/',
    COSMOS_PACKAGES         : '/cosmos/packages/',
    VALIDATE_COSMOS_PACKAGE : '/cosmos/validate-package/',
    SELLER_PAYMENT          : '/report/payments/',
    REFUND                  : '/event/refund/'


    
};
